### ISSUE TITLE
3D in VMs: one solution for itksnap 3.2.0 

### ISSUE THREAD

**Issue by stowler** [CVNRneuroimaging/infrastructure#101]
F, 20141212:
===============
Due to opengl errors, itksnap 3.2.0 has been unusable within virtualbox. True for multiple combinations of host OS, guest linux flavor, guest mesa versions, virtualbox hypervisor version, and virtualbox guest additions. In most cases, when itksnap 3.2.0 was broken, so was 3D in R (rgl).

Below is a description of my first successful work-around, which produced a working itksnap 3.2.0 but may turn out to be suboptimal in ways I haven't seen yet:

- **hypervisor**: vmware fusion Professional Version 7.1.0 (2314774), 3D option enabled
- **host OS**: mac os yosemite 10.10.1 ($uname -a : `Darwin arefrmbp.local 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_641`)
- **guest OS**: fedora 21 ($ uname -a : `Linux localhost.localdomain 3.17.4-302.fc21.x86_64 #1 SMP Thu Dec 4 19:12:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`)

1) Create new vmware fusion VM from iso (`Fedora-Live-MATE_Compiz-x86_64-21-5.iso`).

2) Boot the new VM and update the guest OS:
```bash
$ sudo yum update
$ sudo shutdown -r now 
```

3) After that reboot, install the following packages as prerequisites for 3D and the vmware guest tools. At the moment I don't know that they're *all* strictly required, but this is what got me to this first working install:
```bash
$ sudo yum install mesa-libGL-devel xorg-x11-server-devel xorg-x11-util-macros 
$ sudo yum install libXrender-devel 
$ sudo yum install automake gcc libtool expat-devel kernel-devel git-core 
$ sudo yum install makedepend flex bison
$ sudo shutdown -r
```

4) After that reboot, install the guest's vmware tools. Start with the point-and-click vmware host menu: "Virtual Machine" -> "Install VMware Tools" to make the tools archive available in the guest. Then uncompress the resulting archive within guest OS, and run these commands in the guest:
```bash
$ cd vmware-tools-distrib/
$ sudo ./vmware-install.pl #...accept defaults to interactive install questions
$ /usr/bin/vmware-user 
$ sudo shutdown -r now
```

5) Install itksnap 3.2.0 from the [downloadable binary](http://www.itksnap.org/pmwiki/pmwiki.php?n=Downloads.SNAP3) (mine: `itksnap-3.2.0-20141023-Linux-x86_64.tar.gz`).

@kmcgregor123456 and @rrmm : I'm tagging you here just as an FYI, as I recall that @smtran has previously asked for your help with itksnap in VMs and may ask again in the future.

**Comment by stowler** [comment]
Covered gl errors in person w/ Keith and Rob today (tearing, lagging behind moved/resized window chrome, etc.)

**Comment by lalithvaka** [comment]
Hi @stowler , am in the process of enabling itk-snap for our users on a RHEL VM. I see you have posted some work around with Fedora on VMWare. Do you have any recommendations on how to address this for a RHEL OS on a VMWare VM? I followed the Linux install steps on ITK-Snap site and getting the following error. Thanks for your help.
```
[root@cnpdcmlmscadm002 ~]# itksnap
QXcbConnection: Could not connect to display
Aborted (core dumped)
```
