### ISSUE TITLE
Unable to read text and html files

### ISSUE THREAD

**Issue by smtran** [CVNRneuroimaging/infrastructure#102]
Hi Keith and Rob,

I encountered an "input/output error" when attempting to 1) pull up the FBIRN report on firefox and 2) read a text file. 

1) In trying to review some qc stuff, I was unable to pull up the FBIRN report. I changed to the directory that the report is located (e.g., /data/birc/Atlanta/tranThesis/03.derivedData/qualityControl/MA010/sessA/language/qcReport-FBIRN), then I executed this command: firefox index.html & 
It only opened a firefox browser but did not display anything. 
Attempting to open the index.html file in the file menu on firefox yielded the same result. 

2) In trying to read a text file, I used the command: vim runAllProcScriptsInSerial20141027.sh 
(Directory: /data/birc/Atlanta/tranThesis/gitRepos/thesis/afniProcScripts/)
It opened an empty file instead of the script I had written. The cat command yielded the same "input/output error." 
This error occurs for this file and other files in this folder but not the most recent file in this folder (runProcScripts_8Participants20141204.sh).
The screenshot shows the error message and the permissions of the files in this folder. 

Tagging @stowler to this issue. 

![screenshot 34](https://cloud.githubusercontent.com/assets/5789486/5573196/0183bf38-8f77-11e4-94b5-40f8e8583e1f.png)

Thanks!

**Comment by kmcgregor123456** [comment]
@smtran you can close
