### ISSUE TITLE
telomere - please add service to automatically recover from OSIRIX-down conditions

### ISSUE THREAD

**Issue by stowler** [CVNRneuroimaging/infrastructure#105]
Hi @kmcgregor123456 and @rrmm . Telomere's osirix crashed or was accidentally closed by a user. This interferes with Michael's and our investigators' workflows. (Obviously.)

Please configure a telomere service to keep osirix running at all times. You will need a way to manually disable the service for osirix upgrades and system maintenance.

Thanks,
ST

**Comment by stowler** [comment]
@kmcgregor123456 and @rrmm It happened again: Madeleine wasn't able to send her two sessions' images yesterday. I logged in this morning and found that the dicom receiver (osirix) was not running.

**Comment by kmcgregor123456** [comment]
Setup a plist entry on launchd to handle crashes

**Comment by stowler** [comment]
Please document how to disenable & re-enable for maintenance that requires osirix to be closed.

**Comment by kmcgregor123456** [comment]
OSIRIX will automatically open at BOOT using the .plist launchd daemon. Additionally, it will check every 30 seconds to poll if the app is running. If not, launchd will open the app.

**Comment by kmcgregor123456** [comment]
complete
