### ISSUE TITLE
telomere: please configure remote alerts

### ISSUE THREAD

**Issue by stowler** [CVNRneuroimaging/infrastructure#106]
Hi @kmcgregor123456 and @rrmm . Please configure remote alerts for telomere so that Michael and our investigators don't get delayed by telomere outages.

At minimum you'll want network-level monitoring of the FQDN, and even better would be remote checking for telomere's DICOM receiver service.

The remote alert recipient should be the admin for telomere, which is currently Keith.

Thanks,
ST

**Comment by kmcgregor123456** [comment]
can be folded into #105

**Comment by kmcgregor123456** [comment]
Close
