### ISSUE TITLE
Keith's xubuntu VM: please install software before I resume testing

### ISSUE THREAD

**Issue by stowler** [CVNRneuroimaging/infrastructure#107]
@kmcgregor123456 and @rrmm : I started testing Keith's VM per his request. (/data/birc/Atlanta/IT_STUFF/XubuntuBirc021015_LDAP).

I was able to log-in using the stowler ID Keith created for me this morning. AFNI is installed but It looks like FSL hasn't been correctly installed (screenshot attached). 

Let me know once you've done a complete software install and some initial testing yourselves. After that happens I'll be happy to test for you.

Please provide future versions in OVF/OVA format for portability.

Items to install and test for next deployment:

- sudo access for my user (or whatever install scheme you want to use)
- packages for basic scripting/admin environment: vim git curl wget tmux tree htop slurm imagemagick
- R and rstudio (latest releases)
- itksnap latest release or at least unbroken release (requires careful install of hypervisor guest additions)
- fsl (latest release)
- fsl feeds (matching fsl's latest release)
- afni (latest compile) and afni atlases (may be separate package in neurodebian)
- freesurfer 5.3.0 HCP (ftp://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/5.3.0-HCP)
- mricron (latest release)

![fslnotinstalledornotconfigured](https://cloud.githubusercontent.com/assets/436181/6156784/992cdc88-b20a-11e4-9286-ed09caeeb445.png)

**Comment by stowler** [comment]
...also the BXH/XCEDE tools: http://www.nitrc.org/projects/bxh_xcede_tools

**Comment by kmcgregor123456** [comment]
@rrmm could you handle this request. I'm still working on the GABA protocol and Camille Vaughan's pilot

**Comment by kmcgregor123456** [comment]
Tested the image on my mac mini again. much more successful.

**Comment by kmcgregor123456** [comment]
Completed AFNI and FSL analysis using existing image on Larry and Ralph in addition to booting from Mac. 

Had to download and install pyqt4 to enable afni_proc gui scripts.

Overall, VM environment is stable as implemented in vmware. 
Motif screen redraws are annoying in AFNI, but not debilitating.
