### ISSUE TITLE
pano and qball3 (and other hosts?) no longer allowing remote X11

### ISSUE THREAD

**Issue by stowler** [CVNRneuroimaging/infrastructure#108]
Can no longer run remote X apps hosted by pano and qball3 (and maybe other servers?)

Tested from localhosts including 10.10 mac (user: stowler), 10.9 mac (user: stowler), and x2go session on qball2 (user: stowler).

Removing ~/.Xauthority does not resolve.

[10:53:10]-[stowler]-at-[pano]-in-[~]
$ xeyes
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
Error: Can't open display: localhost:10.0

**Comment by kmcgregor123456** [comment]
Disk space issue with /netusers

Created new lv /export/netuser and copying data from netusers over to /netuser.  Will later unmount /netuser and rename /export/netuser to /export/netusers

**Comment by kmcgregor123456** [comment]
I need to remount hippostore's NFS mount points.

**Comment by smtran** [comment]
This! This again: unable to run remote X apps hosted by qball3. 
![wrong auth](https://cloud.githubusercontent.com/assets/5789486/6317005/a69c7254-ba0a-11e4-9f11-4fc98a2aed22.PNG)

**Comment by kmcgregor123456** [comment]
Fixed. The nfs handle was stale

**Comment by kmcgregor123456** [comment]
Qball3 and pano should now be stable on the new 2TB userhome

**Comment by kmcgregor123456** [comment]
Close
