### ISSUE TITLE
please configure partition space monitoring and alerting for all hippostore partitions

### ISSUE THREAD

**Issue by stowler** [CVNRneuroimaging/infrastructure#109]
Keith and Rob @kmcgregor123456 and @rrmm ,

Please configure disk monitoring and alerting for all hippostore partitions (and preferably for *all* linux server and workstation partitions).

I asked for a /netusers size increase on December 11, it never happened, and today /netusers filled up, resulting in lost time while Stella and I troubleshot the X11 side-effects in the middle of a meeting (issue #108), and I'm losing more time trying to figure out what batch jobs were affected by the full partition.

Alerting on low disk space would have saved all of this time. Last August I strongly recommended that you implement monitoring and alerting. From issue #76: ''I recommend you configure and maintain minute-to-minute monitoring of desktop and server resources (network, CPU, ram, IO, partitions, etc.). I like zabbix but use whatever you're comfortable with."

I suggest that both admins and users receive the disk space alerts so that users can halt their batch jobs at a known stopping point until the low partition space condition is resolved.

**Comment by stowler** [comment]
Emailed update to users per verbal from Keith:

Keith freed 20 GB on the /netusers partition of our server (which is where you home directories are). Per Keith, this week you'll continue using servers and workstations as usual, and then this weekend Keith will make a large change:

1. All week this week, watch that the /netusers (home directories) available space doesn't get too low. The command is "df -h", and you'll look under the "Avail" column on the /netusers row. If you see that available space gets below 5 GB, notify Keith.
2. Complete all processing jobs and close all files by 7pm on Friday Feb 20.
3. That night Keith will copy the current state of everything in /netusers to a new (larger, expandable) disk partition
4. Over the weekend Keith will point all servers and desktops to the new partition, test, and send an email to everyone letting them know that they're OK to resume work on Monday.

**Comment by stowler** [comment]
Emailed Keith and Rob @kmcgregor123456 @rrmm :

I'm going to be working on pano and potentially qball3 through Monday, but as local user stowler-local. That $HOME will be on local disk, so it won't interfere with your weekend netusers NFS work. 

So please bounce those hosts' NFS mounts as needed, just don't reboot.

Thanks,
Stephen

**Comment by stowler** [comment]
Hi Keith and Rob @kmcgregor123456 and @rrmm ,

Just FYI: I apt-get dist-upgrade'd pano and rebooted. I know it sounds crazy, but after Keith's NFS work pano was was running *extremely* slow for local user stowler-local despite no significant CPU, RAM, eth, or local disk loads.

Seems to be running fine after reboot. I have a bunch of freesurfer reconstructions running on it now.

**Comment by kmcgregor123456** [comment]
THanks for the update. I think the it was likely orphaned RPC calls with the stale NFS. Simone's account was slow to respond as well.
