### ISSUE TITLE
Accessing TrackVis

### ISSUE THREAD

**Issue by simonero** [CVNRneuroimaging/infrastructure#110]
TrackVis is currently installed on Pano.  I have been able to use it since installation but not without major difficulties.

I was able to resolve the primary problem causing a segmentation fault/core dump when opening most .trk files by killing a trackvis process that was recognized as running although not listed after using the "pidof trackvis" command and not tied to any actual open processes.  This solved half of my problem, but I am still having major issues with the program itself.

More than half of the time that I open the program (with "trackvis", "trackvis [file]", "trackvis -new", or "trackvis -new [file]") I am unable to open a .trk file and view tracts.  The screen stays grey but doesn't appear to still be loading.  I am no longer getting regular segmentation fault/core dump errors, but did get one the other day after viewing several tracts/ROIs in one window.

Any idea what could be causing this problem or how I can fix it?  Could the fact I have to remote into Pano instead of qball play any part in this?  Perhaps installing the program differently so it can be accessed from any computer would help? - and, in general, that would be extremely useful in case Pano is ever down or occupied when I'm in the lab.

Note: I am running the most recent version of TrackVis and file size does not seem to determine when I do/don't have issues.  I've also tried searching for this issue online and found nothing; unless I am not using the right combination of search queries, this doesn't seem to be a common/widespread problem.

Thanks!!!

Simone

**Comment by kmcgregor123456** [comment]
@simonero 
I will take a look at it. It is highly likely that the X transfers between machines is causing these segfaults. However, without more investigation, I cannot say for certain.

TrackVis will be installed on our new image. I will install it on qball3, as well, though I thought it was on there already. The X2Go might be goofy with it though. we'll see

**Comment by simonero** [comment]
I've actually been using XQuartz, X2Go never functioned properly.  Not sure if that makes any difference?

**Comment by stowler** [comment]
Status?

**Comment by kmcgregor123456** [comment]
I'll look at it tomorrow

**Comment by simonero** [comment]
Looked at TrackVis/X2GO with @kmcgregor123456.  (Thank you!!)

X2GO is working fine on my laptop when connected to qball1, provided we take TrackVis out of the equation...

We determined a few things about TrackVis: it seems to be the best/only real software option; it is an orphaned, closed-source project; for some strange reason nobody cares.  Also, opening up a 998M .trk file uses up 47% of the memory.

As of now, to my understanding the plan is to set me up on my own machine because of the high processing demands and numerous bugs associated with TrackVis.

For Keith's record, I believe IDL is actually the only other program I need installed that isn't standard or probably on all systems already.

**Comment by simonero** [comment]
@kmcgregor123456, new, exciting TrackVis development!!  It was updated!!?  There's no information on the website yet that I can see, or in a Google search of "trackvis update 2015" for this past week, but a dialogue box opened when I opened the program just now.  Almost sketchy really, but this notification is directly through the program.  It asked me if I'd like to download the latest version.  I tried to download the file, but was denied: "Download failed: forbidden".

I'm guessing my permissions prevent me from downloading this file??  If you are able to download it and it's compatible (there are notes about this in the update details) lets try it out??  To get to it, if it doesn't pop up automatically, go to [command line:]trackvis > Help > Check for Updates.  If "trackvis" won't open per glitches, try "trackvis -new".

This is great!!

**Comment by kmcgregor123456** [comment]
I'll take care of it

Best,

-------------------
Keith McGregor, PhD
Atlanta VA CVNR
Emory University
www.varrd.emory.edu<http://ww.varrd.emory.edu>


On Mar 20, 2015, at 12:25 AM, simonero <notifications@github.com<mailto:notifications@github.com>> wrote:


@kmcgregor123456<https://github.com/kmcgregor123456>, new, exciting TrackVis development!! It was updated!!? There's no information on the website yet that I can see, or in a Google search of "trackvis update 2015" for this past week, but a dialogue box opened when I opened the program just now. Almost sketchy really, but this notification is directly through the program. It asked me if I'd like to download the latest version. I tried to download the file, but was denied: "Download failed: forbidden".

I'm guessing my permissions prevent me from downloading this file?? If you are able to download it and it's compatible (there are notes about this in the update details) lets try it out?? To get to it, if it doesn't pop up automatically, go to [command line:]trackvis > Help > Check for Updates. If "trackvis" won't open per glitches, try "trackvis -new".

This is great!!

—
Reply to this email directly or view it on GitHub<https://github.com/CVNRneuroimaging/infrastructure/issues/110#issuecomment-83942662>.

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).

**Comment by stowler** [comment]
Hi Keith  @kmcgregor123456 : Status?

**Comment by kmcgregor123456** [comment]
Updated and installed new version of trackvis
