### ISSUE TITLE
please resolve for Stella: AFNI crashes in x2go

### ISSUE THREAD

**Issue by stowler** [CVNRneuroimaging/infrastructure#115]
Hi Rob and Keith @rrmm @kmcgregor123456 ,

Please help Stella @smtran  resolve AFNI crashes that are holding up her data inspection. Occurs in x2go sessions when she connects to (and/or originates?) x2go session from her GSU Windows 8 host, but not when she connects from her Windows 8 laptop. Also does not occur in ssh-forwarded sessions outside of x2go.

Tested with her today:
- AFNI launched as stran5@qball3
- ...which is within an ssh connection from stella-local@qball2 running a qball2 x2go session
- ...which she connected to via her GSU Windows 8 x2go client software

Three specific steps to crash AFNI as stran5@qball3: 

1.  open the AFNI GUI using command `afni /data/birc/Atlanta/tranThesis/03.derivedData/applyGLM/batch-20150313173303/result
s.MA023.motor.onsetsBlock`,
2. change the overlay to  `stats.MA023.motor.onsetsBlock_REML` , then change sub-bricks for overlay and threshold to F-stat, 
3. attempt to threshold using the slider

I recommend that you setup a google hangout with Stella while she's at GSU so that she can screenshare the affected x2go sessions with you.

Thanks,
Stephen.

**Comment by stowler** [comment]
Rob @rrmm briefed me on progress. I suggested that he or Stella arrange for a GSU desktop admin to be in the GSU room for their next call in order to provide admin access for 

1) Rob's next diagnostics, and/or 
2) installation of virtualbox, from within which Rob can provide Stella with a more controllable x2go client environment.

**Comment by smtran** [comment]
Update for @rrmm & @stowler 

Issue resolved: Using mstsc to remote to pano via Larry (per Keith), AFNI does not crash. 
Thanks!
Stella
