### ISSUE TITLE
Permissions Issue?  Can't do work on server.

### ISSUE THREAD

**Issue by simonero** [CVNRneuroimaging/infrastructure#124]
I am getting a strange issue...  even though I'm listed as the owner, I can't do a thing (mv, cp, mkdir, 3dAFNItoNIFTI, fslview) in my folders on the Emory server.  I am not doing anything different and last successfully accessed many folders in my subdirectory about 4 hours ago.  I am ssh'ing into pano, which I always do.  I also tried qball3.  Help??!

This happens for the below path + /netusers/srrobe3

This is what happens when I try to create a folder, as an example:
/data/birc/Atlanta/simoneTracts
srrobe3@pano:/data/birc/Atlanta/simoneTracts$ mkdir testing
mkdir: cannot create directory `testing': Read-only file system
srrobe3@pano:/data/birc/Atlanta/simoneTracts$ 

If I try to sudo (I tried changing ownership/permissions), this happens:
srrobe3@pano:/data/birc/Atlanta/simoneTracts$ sudo mkdir testing
[sudo] password for srrobe3: 
srrobe3 is not in the sudoers file.  This incident will be reported.
srrobe3@pano:/data/birc/Atlanta/simoneTracts$ 

This is what happens if I try to open firefox to send myself files:
srrobe3@pano:/data/birc/Atlanta/simoneTracts$ firefox
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
Error: cannot open display: localhost:13.0

or, <<top is Xquartz, bottom is terminal>>

srrobe3@pano:~$ firefox
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
Error: cannot open display: localhost:14.0

The errors above are the same as for fslview.

/data/birc/Atlanta/simoneTracts
srrobe3@pano:/data/birc/Atlanta/simoneTracts$ ls -l
total 8
drwxr-xr-x  8 srrobe3    10021 4096 Apr  1 15:57 00.Supporting_Files
drwxr-xr-x 32 srrobe3 centrify 4096 Jun 26 21:00 01.Subjects

**Comment by kmcgregor123456** [comment]
@simonero Close please. fixed with previous RAID repair

**Comment by simonero** [comment]
I'm still having permissions issues.  Unable to do any work within my subfolder /data/birc/Atlanta/simoneTracts

**Comment by kmcgregor123456** [comment]
Try now

Best,

-------------------
Keith McGregor, PhD
Atlanta VA CVNR
Emory University
www.varrd.emory.edu<http://ww.varrd.emory.edu>


On Aug 1, 2015, at 8:26 PM, simonero <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm still having permissions issues. Unable to do any work within my subfolder /data/birc/Atlanta/simoneTracts

—
Reply to this email directly or view it on GitHub<https://github.com/CVNRneuroimaging/infrastructure/issues/124#issuecomment-126966081>.

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).

**Comment by simonero** [comment]
Seems to be working.  Thank you!!

Best,
Simone

**Comment by kmcgregor123456** [comment]
@simonero close please
