### ISSUE TITLE
More issues.... no idea what's going on here

### ISSUE THREAD

**Issue by simonero** [CVNRneuroimaging/infrastructure#132]
I was using pano fine earlier.  I logged on to check on the status of a process I was running from GSU and get these errors, both on pano and qball3:

-bash: /netusers/srrobe3/.profile: Input/output error

srrobe3@qball3:/data/birc/Atlanta$ ls   
ls: reading directory .: Input/output error
srrobe3@qball3:/data/birc/Atlanta$ ls -lh
ls: reading directory .: Input/output error
total 0

Folders are gone or can't be accessed.

What's going on?  Does this mean everything I did today is gone?  =(

**Comment by rrmm** [comment]
hippostore's raid card seems to have error'ed out.   The filesystems are currently read-only.

**Comment by kmcgregor123456** [comment]
@simonero close please
