### ISSUE TITLE
Keith please create a sponsored account for Lisa CK

### ISSUE THREAD

**Issue by stowler** [CVNRneuroimaging/infrastructure#137]
Hi Keith @kmcgregor123456 ,

Lisa Crystal Krishnamurthy juts confirmed that she does not currently have an emory account. Would you mind creating a sponsored account for her? If you're able to do it quickly enough I might be able to get her security handled in time for her to participate in Friday's group maintenance.

Thanks,
Stephen

**Comment by kmcgregor123456** [comment]
Order placed.
RITM40262<https://emory.service-now.com/ess/sc_req_item.do?sys_id=19bc391a2bb102c0979f18d119da1580&sysparm_view=ess>
Sponsored Account Request: Person or Department
        2015-08-14






================
Keith McGregor, PhD
VA RR&D Atlanta CoE
Emory University
352.359.8084
www.varrd.emory.edu
________________________________

**Comment by kmcgregor123456** [comment]
complete. close please
