### ISSUE TITLE
configuring rama as stand-alone workstation

### ISSUE THREAD

**Issue by stowler** [CVNRneuroimaging/infrastructure#139]
Keith and Rob @kmcgregor123456 @rrmm ,

Just FYI on Friday Keith paved-over rama and installed 14.04, and today I began configuring its apps as the next step toward using it as a stand-alone workstation. I'll do more tmw but my notes from today are here:

https://github.com/CVNRneuroimaging/infrastructure/blob/master/config/notes/20150817-stowlerBircSystemConfig.md

It's available to be powered down, as Keith is going to replace its battery today/tonight and add storage.

I'll use this issue to update you if I make an significant config changes to it after Keith's post-battery/storage reboot.

Thanks,
Stephen

## Saturday the 22nd:
- [x] install nvidia and quad-monitor support
- [x] install and test matlab
- [x] initial troubleshooting of console that can't be unlocked

## Sunday the 23rd:
- [x] R: tested
- [x] FSL: configured
- [x] FSL: tested
- [x] FSL FIX: installed
- [x] FSL FIX: tested
- [ ] MELODIC: test group ICA (skipping for now: already performed 12h tests on pano)

## Monday the 24th
- [x] gridengine: install for single-host parallel processing

## Tuesday the 25th through ?
- [x] ssh key fixes
- [x] gridengine: configure FSL work-around
- [x] gridengine: test on MELODIC group ICA
- [x] melview: installed and tested

## Wednesday the 26th 
- [x] installed and tested FBIRN tools
- [x] configured AFNI
- [ ] TBD: troubleshoot environment variables (/etc/bash.bashrc not being respected)

## Thursday the 27th through ...?

_My config work on rama is on hold for a few days but Rob might continue to work on non-app issues_

**Comment by stowler** [comment]
Keith @kmcgregor123456 replaced UPS battery this evening and rebooted but rama isn't currently reachable. -ST

**Comment by stowler** [comment]
Rama is back up.

```
[10:39:15]-[stowler-local]-at-[rama]-in-[~]
$ uptime
 22:39:17 up 30 min,  1 user,  load average: 0.08, 0.03, 0.05
```

**Comment by stowler** [comment]
Keith installed new UPS on Monday but didn't run it to Emory's emergency power. Emailed Keith, Lisa, Kevin, Cheryl:

> Is someone available to check the CVNR cave for an extension cord? I'm over in WMB looking for one that is > 45' and labeled as rated for at least 12A. Indoor or outdoor, doesn't matter.

>Thanks!
>Stephen

**Comment by stowler** [comment]
FYI: will be committing today's (Saturday's) rama config and testing notes here:

https://github.com/CVNRneuroimaging/infrastructure/blob/master/config/notes/20150822-stowlerBircSystemConfig.md

**Comment by stowler** [comment]
FYI: will be committing today's (Sunday's) rama config and testing notes here:

https://github.com/CVNRneuroimaging/infrastructure/blob/master/config/notes/20150823-stowlerBircSystemConfig.md

**Comment by stowler** [comment]
FYI: will be committing today's (Monday's) rama config and testing notes here:

https://github.com/CVNRneuroimaging/infrastructure/blob/master/config/notes/20150824-stowlerBircSystemConfig.md

**Comment by stowler** [comment]
FYI: will be committing today's (Tuesday's) rama config and testing notes here:

https://github.com/CVNRneuroimaging/infrastructure/blob/master/config/notes/20150825-stowlerBircSystemConfig.md

**Comment by stowler** [comment]
Keith: Rob is actively working on pano today (Wednesday), rebooting-at-will. That means I'm reliant solely on rama for today so please don't reboot it or make any system changes. Thanks, ST

cc: @kmcgregor123456

**Comment by stowler** [comment]
Application work on rama has been temporarily deprioritized. After Tuesday 9/1 I might be available to resume work to bring it to parity with pano.

**Comment by stowler** [comment]
Messaged Rob in the console ticket: 
>Hi Rob. If it's OK with you, later tonight I'm going to take over pano and rama until Thursday morning. I need them for Tuesday and Wednesday data reviews, and am going to start mount, read, and prep tonight.

**Comment by stowler** [comment]
FYI, no response needed: rebooting rama...last night and continuing into this morning `vim` launches hang indefinitely. Can't be explained by network mount problems nor full local partitions:

```bash
[06:58:21]-[stowler-local]-at-[rama]-in-[~]
$ df -h
Filesystem                    Size  Used Avail Use% Mounted on
/dev/mapper/xubuntu--vg-root  411G  135G  256G  35% /
none                          4.0K     0  4.0K   0% /sys/fs/cgroup
udev                           24G  4.0K   24G   1% /dev
tmpfs                         4.8G  1.6M  4.8G   1% /run
none                          5.0M     0  5.0M   0% /run/lock
none                           24G  168K   24G   1% /run/shm
none                          100M   88K  100M   1% /run/user
/dev/sda1                     236M   69M  155M  31% /boot

[06:58:24]-[stowler-local]-at-[rama]-in-[~]
$ mount
/dev/mapper/xubuntu--vg-root on / type ext4 (rw,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
/dev/sda1 on /boot type ext2 (rw)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)

[06:58:29]-[stowler-local]-at-[rama]-in-[~]
$ sudo shutdown -r now
```

**Comment by rrmm** [comment]
if it continues to happen, using strace(1) to a file might be useful in diagnosing.

**Comment by stowler** [comment]
Just FYI, no action needed: Chuck from facilities says that we have no emergency power outlets in WMB6205 (even the ones with square red sticker), so this morning I moved rama's UPS off of its too-thin between-room extension cord and back to a nearby outlet. Its UPS handled the < 10 s outage just fine.

**Comment by kmcgregor123456** [comment]
Have the 3tb hard drive


================
Keith McGregor, PhD
VA RR&D Atlanta CoE
Emory University
352.359.8084
www.varrd.emory.edu
________________________________

**Comment by stowler** [comment]
FYI: rsyncs from pano to rama's 3TB external drive failing. Keith provided 5 TB drive and 2 TB drive along with a dual-slot cradle (pano not accepting this cradle for some reason). Trying rsync again after configuring these drives in rama's `fstab`:

```
# 5 TB external drive. Realize that this is a misnomer, but it is so in order to
# manage historical factors: CDA processing was moved back and forth between
# pano and rama as needed.
/dev/sdc1 /data/panolocal ext4 rw 0 0

# 2 TB external drive:
/dev/sdb1 /data/ramalocal ext4 rw 0 0
```
