### ISSUE TITLE
Freesurfer License

### ISSUE THREAD

**Issue by simonero** [CVNRneuroimaging/infrastructure#143]
I can't use freesurfer on qball3 because the license file is missing.  It needs to be in $FREESURFER_HOME.  I can't do it myself because of permissions restrictions.

I also can't use it on qball4 because I don't have permissions to "subjects".

I put a copy of my license file on the server in this location:

/data/birc/Atlanta/simoneTracts/00.Supporting_Files/license.txt

The name of the file needs to stay the same.  I set it to full permissions (777) so other people could use the license as well.

Thanks!!

**Comment by kmcgregor123456** [comment]
I will fix.


================
Keith McGregor, PhD
VA RR&D Atlanta CoE
Emory University
352.359.8084
www.varrd.emory.edu
________________________________

**Comment by kmcgregor123456** [comment]
added the necessary license files and changed the permissions. try now

**Comment by kmcgregor123456** [comment]
close after testing

**Comment by simonero** [comment]
Thank you Keith!!  Thumbs up for qball3.  Will close this as soon as I've tested qball4.

**Comment by simonero** [comment]
qball4 freesurfer test failed quickly at "-autorecon1" phase.

This issue is not mirrored by qball3 for the same subject.

Here is the log text:

#|---------------------------------------------------------------



New invocation of recon-all 



Fri Aug 28 09:24:22 EDT 2015
/usr/local/freesurfer/subjects/s210
/usr/local/freesurfer/bin/recon-all
-s s210 -autorecon1
subjid s210
setenv SUBJECTS_DIR /usr/local/freesurfer/subjects
FREESURFER_HOME /usr/local/freesurfer
Actual FREESURFER_HOME /usr/local/freesurfer
build-stamp.txt: freesurfer-Linux-centos6_x86_64-stable-pub-v5.3.0
Linux qball4.birc.emory.edu 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
cputime      unlimited
filesize     unlimited
datasize     unlimited
stacksize    8192 kbytes
coredumpsize 0 kbytes
memoryuse    unlimited
vmemoryuse   unlimited
descriptors  1024 
memorylocked 64 kbytes
maxproc      192649 
maxlocks     unlimited
maxsignal    192649 
maxmessage   819200 
maxnice      0 
maxrtprio    0 
maxrttime    unlimited

             total       used       free     shared    buffers     cached
Mem:      24680696   20705160    3975536      58724     237408   18409332
-/+ buffers/cache:    2058420   22622276
Swap:     25154556     108568   25045988

########################################
program versions used
$Id: recon-all,v 1.379.2.73 2013/05/12 23:15:37 nicks Exp $
$Id: mri_motion_correct.fsl,v 1.14 2011/03/02 20:16:39 nicks Exp $
mri_convert -all-info 
ProgramName: mri_convert  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:22-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_convert.c,v 1.179.2.7 2012/09/05 21:55:16 mreuter Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
FLIRT version 5.5
$Id: talairach_avi,v 1.9 2011/03/02 18:38:06 nicks Exp $
mri_convert --version 
stable5
ProgramName: tkregister2_cmdl  ProgramArguments: --all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:23-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: tkregister2.c,v 1.121.2.1 2011/03/28 20:25:16 greve Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
Program nu_correct, built from:
Package MNI N3, version 1.10, compiled by nicks@minerva (x86_64-unknown-linux-gnu) on 2010-02-20 at 17:32:37
ProgramName: mri_make_uchar  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:23-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_make_uchar.c,v 1.4 2011/03/02 00:04:14 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mri_normalize  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:23-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_normalize.c,v 1.73.2.1 2012/10/17 19:11:32 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mri_watershed  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:23-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_watershed.cpp,v 1.96.2.1 2011/11/08 22:18:44 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mri_gcut  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:23-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_gcut.cpp,v 1.14 2011/03/02 00:04:16 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mri_segment  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:23-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_segment.c,v 1.40 2011/03/02 00:04:24 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mri_label2label  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:23-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_label2label.c,v 1.40.2.2 2013/04/02 16:26:15 greve Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 


 ======= NUMBER OF OPENMP THREADS = 1 ======= 
ProgramName: mri_em_register  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:24-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_em_register.c,v 1.84.2.3 2013/02/09 00:49:26 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mri_ca_normalize  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:24-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_ca_normalize.c,v 1.52.2.2 2012/10/17 19:11:32 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mri_ca_register  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:24-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_ca_register.c,v 1.78.2.3 2013/02/09 00:42:20 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mri_ca_label  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:24-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_ca_label.c,v 1.96.2.1 2012/08/28 22:11:20 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mri_pretess  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:24-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_pretess.c,v 1.20 2011/03/02 00:04:23 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mri_fill  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:24-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_fill.c,v 1.118 2011/03/16 21:23:49 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mri_tessellate  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:25-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_tessellate.c,v 1.36 2011/03/02 00:04:25 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mri_concatenate_lta  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:25-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_concatenate_lta.c,v 1.10 2011/03/16 21:23:48 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mri_normalize_tp2  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:25-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_normalize_tp2.c,v 1.8 2011/03/02 00:04:23 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mris_smooth  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:25-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mris_smooth.c,v 1.28 2011/03/02 00:04:34 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mris_inflate  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:25-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mris_inflate.c,v 1.43 2011/03/02 00:04:32 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mris_curvature  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:25-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mris_curvature.c,v 1.31 2011/03/02 00:04:30 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mris_sphere  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:25-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mris_sphere.c,v 1.57 2011/03/02 00:04:34 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mris_fix_topology  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:25-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mris_fix_topology.c,v 1.48 2011/03/02 00:04:32 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mris_topo_fixer  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:26-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mris_topo_fixer.cpp,v 1.29 2011/03/02 00:04:34 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mris_ca_label  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:26-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mris_ca_label.c,v 1.35 2011/03/02 00:04:27 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mris_euler_number  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:26-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mris_euler_number.c,v 1.8.2.2 2013/01/14 22:40:07 greve Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mris_make_surfaces  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:26-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mris_make_surfaces.c,v 1.127.2.6 2013/05/12 22:28:01 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mris_register  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:26-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mris_register.c,v 1.59 2011/03/02 00:04:33 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mris_volmask  ProgramArguments: --all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:26-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mris_volmask.cpp,v 1.25 2011/03/02 00:04:34 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mris_anatomical_stats  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:26-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mris_anatomical_stats.c,v 1.72 2011/03/02 00:04:26 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mrisp_paint  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:26-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mrisp_paint.c,v 1.11 2011/03/02 00:04:35 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mris_curvature_stats  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:26-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mris_curvature_stats.c,v 1.64 2011/03/02 00:04:30 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mris_calc  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:27-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mris_calc.c,v 1.37.2.8 2013/01/28 17:05:17 greve Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
$Id: mri_robust_register.cpp,v 1.52.2.3 2012/11/20 17:26:47 mreuter Exp $

ProgramName: mri_robust_register  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:27-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_robust_register.cpp,v 1.52.2.3 2012/11/20 17:26:47 mreuter Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
$Id: mri_robust_template.cpp,v 1.37.2.2 2012/10/10 19:59:06 mreuter Exp $

ProgramName: mri_robust_template  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:27-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_robust_template.cpp,v 1.37.2.2 2012/10/10 19:59:06 mreuter Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mri_and  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:27-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_and.c,v 1.4 2011/03/02 00:04:13 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mri_or  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:27-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_or.c,v 1.3 2011/03/02 00:04:13 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mri_fuse_segmentations  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:27-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_fuse_segmentations.c,v 1.8 2011/03/02 00:04:15 nicks Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
ProgramName: mri_segstats  ProgramArguments: -all-info  ProgramVersion: $Name: stable5 $  TimeStamp: 2015/08/28-13:24:27-GMT  BuildTimeStamp: May 13 2013 16:24:28  CVS: $Id: mri_segstats.c,v 1.75.2.9 2013/02/16 00:09:33 greve Exp $  User: simoneroberts  Machine: qball4.birc.emory.edu  Platform: Linux  PlatformVersion: 3.13.0-39-generic  CompilerName: GCC  CompilerVersion: 40400 
#######################################
GCADIR /usr/local/freesurfer/average
GCA RB_all_2008-03-26.gca
GCASkull RB_all_withskull_2008-03-26.gca
AvgCurvTif average.curvature.filled.buckner40.tif
GCSDIR /usr/local/freesurfer/average
GCS curvature.buckner40.filled.desikan_killiany.2010-03-25.gcs
#######################################
#--------------------------------------------
#@# MotionCor Fri Aug 28 09:24:27 EDT 2015
Found 1 runs
/usr/local/freesurfer/subjects/s210/mri/orig/001.mgz
Checking for (invalid) multi-frame inputs...
WARNING: only one run found. This is OK, but motion
correction cannot be performed on one run, so I'll
copy the run to rawavg and continue.

 cp /usr/local/freesurfer/subjects/s210/mri/orig/001.mgz /usr/local/freesurfer/subjects/s210/mri/rawavg.mgz 

/usr/local/freesurfer/subjects/s210

 mri_convert /usr/local/freesurfer/subjects/s210/mri/rawavg.mgz /usr/local/freesurfer/subjects/s210/mri/orig.mgz --conform 

mri_convert /usr/local/freesurfer/subjects/s210/mri/rawavg.mgz /usr/local/freesurfer/subjects/s210/mri/orig.mgz --conform 
$Id: mri_convert.c,v 1.179.2.7 2012/09/05 21:55:16 mreuter Exp $
reading from /usr/local/freesurfer/subjects/s210/mri/rawavg.mgz...
TR=0.00, TE=0.00, TI=0.00, flip angle=0.00
i_ras = (-1, -0, 0)
j_ras = (-0, 1, 0)
k_ras = (-0, -0, 1)
Original Data has (1, 1, 1) mm size and (176, 256, 256) voxels.
Data is conformed to 1 mm size and 256 voxels for all directions
changing data type from short to uchar (noscale = 0)...
MRIchangeType: Building histogram 
Reslicing using trilinear interpolation 
writing to /usr/local/freesurfer/subjects/s210/mri/orig.mgz...

 mri_add_xform_to_header -c /usr/local/freesurfer/subjects/s210/mri/transforms/talairach.xfm /usr/local/freesurfer/subjects/s210/mri/orig.mgz /usr/local/freesurfer/subjects/s210/mri/orig.mgz 

INFO: extension is mgz
#--------------------------------------------
#@# Talairach Fri Aug 28 09:24:41 EDT 2015
/usr/local/freesurfer/subjects/s210/mri

 mri_nu_correct.mni --n 1 --proto-iters 1000 --distance 50 --no-rescale --i orig.mgz --o orig_nu.mgz 

Linux qball4.birc.emory.edu 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

recon-all -s s210 exited with ERRORS at Fri Aug 28 09:24:44 EDT 2015

To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

**Comment by rrmm** [comment]
i can reproduce on qball1 and 4 at least.

note: you probably don't want to put data (even test data) under /usr/local/freesurfer/   (which
should probably not be user writable?).  move the data under a user directory and point the SUBJECTS_DIR variable to match.

one of the subprograms is crashing during run, but doesn't provide terribly good diagnostics.  I'll look into it some more.

**Comment by simonero** [comment]
Reproduce the error or reproduce the expected data?

Which program?  There's a regular issue that occurs on both OS X and Linux during -autorecon2.  Running -cortribbon and then -segstats after -autorecon2, before -autorecon3, solves that issue.  (It's a little annoying but at least it's a consistent fix.)  Is that what you are talking about, or something else??

I'm going to move all of the data I generated into my subject folders on /data/birc/ as soon as I'm done.

**Comment by rrmm** [comment]
reproduce a good run of 'recon-all -autorecon1 -subjid s210' on qball3, 
and a failure on qball1/4 of the same.

**Comment by simonero** [comment]
Are you running recon-all right now?  I got an error when trying to run -autorecon2 for s210 about another instance already running.  If not and it's an error I can kill it.

**Comment by rrmm** [comment]
i'm running in my user dir

**Comment by rrmm** [comment]
I was able to get a successful run on qball4 (only took 14 hours!).

This issue is most likely due to having to query for user info via ldap when doing filesystem ops.
The auth server (or the links in-between) can't keep up.

Installation of nscd on affected hosts seems to cure it for me.

please confirm on qball4, and close if fixed.

**Comment by kmcgregor123456** [comment]
close if corrected
