### ISSUE TITLE
maybe melting: please send zabbix plots for pano and rama

### ISSUE THREAD

**Issue by stowler** [CVNRneuroimaging/infrastructure#145]
Keith and Rob,

Please provide links to the zabbix plots for pano and rama thermals. Memory and aggregate CPU would also be nice. 

I deployed SGE on pano for Bruce's group ICA work. Pano's lower-right LCD died about 20 minutes into the job (so a few minutes before this 17:41 time stamp) :
```
Melodic Started at Mon Aug 24 17:10:16 EDT 2015 :
1008K   /tmp/melFromFeeds-groupICA-FSLPARALLEL-inputsCleaned-temporalCat-structBBR-standard2mmNonlinear.gica
...but melodic not yet finished as of Mon Aug 24 17:41:38 EDT 2015. Will check again in 20 seconds...
```

NVIDIA utility currently shows GPU thermodes at 38 and 48 C.

cc @kmcgregor123456 @rrmm 
![img_0574](https://cloud.githubusercontent.com/assets/436181/9453462/93e7e364-4a88-11e5-8543-5ed72f1c45ca.jpeg)

**Comment by rrmm** [comment]
-added zabbix config for pano/rama
-put in /etc/rc2.d but not tested
-added stowler user/will email password
