### ISSUE TITLE
Can you please install IDL so I can use MAS?

### ISSUE THREAD

**Issue by simonero** [CVNRneuroimaging/infrastructure#146]
Can you pretty please install IDL on qball3 so I can see if using MAS fixes my FA catastrophe?  I'm pretty sure I can just call the most recent MAS from where I have it saved as long as the idl command is recognized.

**Comment by rrmm** [comment]
i put the tar from pano in /opt/idl.  you'll need to use the full path to it.  Do we have a license for it?   mas.sav is also in /opt.

**Comment by simonero** [comment]
This is still an issue, but for qball2 and qball4.  I opened up a new issue thread to reflect that I need both IDL and TrackVis on those machines, so I'm closing this now..
