### ISSUE TITLE
please reset hippoback password for stowler-local

### ISSUE THREAD

**Issue by stowler** [CVNRneuroimaging/infrastructure#147]
Hi Rob. Please reset hippoback password for user stowler-local. Thanks, Stephen

cc: @rrmm

**Comment by stowler** [comment]
...not an emergency, BTW, I still have access to hippoback through pano. It's just that deep recursive file operations take forever over the NFS (especially chown/chmod), and recently I've run into some root squash limitations that are easiest to work-around by ssh'ing directly to hippoback. Thanks, Stephen

**Comment by rrmm** [comment]
done

**Comment by stowler** [comment]
Thanks for such a fast response...and on a Saturday morning!

 Worked: I logged in with temp password and changed it.

Thanks again.
-ST
