### ISSUE TITLE
rsync to pano: am I having a stroke

### ISSUE THREAD

**Issue by stowler** [CVNRneuroimaging/infrastructure#148]
Hi Rob. Can you please confirm that I'm not having a stroke?

Error on host I'm trying to send from (AREF OS X):
```bash
[14:35:05]-[stowler-local]-at-[hal]-in-[/data/panolocal]
$ rsync -avR --progress tmp* stowler-local@pano.birc.emory.edu:${HOME}/tempNetworkXferIntoPano20150901/
Ubuntu 14.04.3 LTS pano.birc.emory.edu ssh-pty

sending incremental file list
rsync: mkdir "/Users/stowler-local/tempNetworkXferIntoPano20150901" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.0]
rsync: [sender] write error: Broken pipe (32)
```

Proof that the target directory exists on the receiving side (pano):
```bash
[14:42:15]-[stowler-local]-at-[pano]-in-[~]
$ ls -ald tempNetworkXferIntoPano20150901
drwxrwxr-x 2 stowler-local stowler-local 4096 Sep  1 14:33 tempNetworkXferIntoPano20150901
```
cc: @rrmm

**Comment by kmcgregor123456** [comment]
recommend you use /tmp/ unless the datasets are over 300GB


================
Keith McGregor, PhD
VA RR&D Atlanta CoE
Emory University
352.359.8084
www.varrd.emory.edu
________________________________

**Comment by rrmm** [comment]
look at the HOME variable.  Looks like /Users vs /home

**Comment by stowler** [comment]
Thanks Keith and Rob. Such a dumb moment on my part. At the time I worked around it by sending to a non-$HOME location on hippoback, but thanks for confirming that I'm not crazy -ST
