### ISSUE TITLE
Configure ralph

### ISSUE THREAD

**Issue by rrmm** [CVNRneuroimaging/infrastructure#153]
ralph.birc.emory.edu's auth should be ready for users

**Comment by kmcgregor123456** [comment]
After I configure it, I'll image it for installs. I need to work on Ralph for about a week to get comfortable

Best,

-------------------
Keith McGregor, PhD
Atlanta VA CVNR
Emory University
www.varrd.emory.edu<http://ww.varrd.emory.edu>


On Oct 1, 2015, at 11:30 PM, rrmm <notifications@github.com<mailto:notifications@github.com>> wrote:


ralph.birc.emory.edu<http://ralph.birc.emory.edu>'s auth should be ready for users

—
Reply to this email directly or view it on GitHub<https://github.com/CVNRneuroimaging/infrastructure/issues/153>.

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).
