### ISSUE TITLE
Need Programs To Do Data Processing

### ISSUE THREAD

**Issue by simonero** [CVNRneuroimaging/infrastructure#154]
I need IDL and Trackvis (latest version) on qball2 and qball4 to process & view my data.

Thank you!

**Comment by rrmm** [comment]
i put them on qball2 in /opt.  the license info for trackvis is in the directory with it.
NB: i soft-linked libmng1 to libmng2 to allow it to link correctly and run.  I don't know 
the ramifications of this, but this is how it was done on qball1.

idl is there too, but you'll need to get a license for it.

**Comment by simonero** [comment]
Thank you.  I don't know anything about those directories but that gives me an idea of how to diagnose any problems that could occur before asking for help.  IDL will run on a limited basis without the license so that's perfectly fine!

Can I get these on qball4 as well?  I use both qballs and also want to make sure that if something goes down again I can continue working on the server.  I have had to do everything on my external recently but I am out of space.

**Comment by rrmm** [comment]
i put the same stuff on qball4 in /opt

**Comment by simonero** [comment]
I am unable to call "trackvis" on either qball2 or qball4.

**Comment by simonero** [comment]
So I searched around for a while and eventually figured out the issue on qball2.  The program was in opt for some reason and the folder had not been exported to the PATH so I could not execute it.  (I have no idea what you are talking about in terms of libmng?  I don't see that folder.)

In the future, if I need to do anything to install the program it would be helpful if you could give me the path to the folder, let me know that I need to edit my .bashrc file, and provide me any additional needed information.  If anything besides defining a variable or exporting to path is involved, I need directions for this or need to know what to look up as well.  This will save me a lot of time.  =)

I haven't troubleshooted IDL, but this is also not a recognized command on either machine.

**Comment by rrmm** [comment]
right they are in /opt, and neither is on the path.

you can go ahead and add them to your path in your bashrc or whichever shell script you
source to setup your environment. 

the idl executable is buried a bit i'll take a look and post the exact path for it.

**Comment by simonero** [comment]
Please tell me exactly how you want me to do these things.  I do not have any background in IT or experience troubleshooting Linux, and I did not set up anything on this Linux environment.

**Comment by kmcgregor123456** [comment]
1) Open vim
2) open .bashrc from your home directory (it's a hidden directory)
3) add the text: export PATH=$PATH:/opt/bin:/opt/:/opt/IDL/        <note: add a colon and then whatever /opt directory has the application you want>
4) Save the .bashrc
5) open a new terminal window


================
Keith McGregor, PhD
VA RR&D Atlanta CoE
Emory University
352.359.8084
http://www.varrd.emory.edu

________________________________

**Comment by rrmm** [comment]
* the full paths to the binaries are
`/opt/idl/idl/bin/idl` and `/opt/trackvis/trackvis`

They can be run by typing the above full paths at the prompt.

To get these in your path you need to add /opt/idl/idl/bin and /opt/trackvis to your path environment variable.  The path variable is an environment variable which contains a colon-delimited set of directories the shell will search when you type a command at the prompt.

* to modify the path variable at the command prompt (which applies to that shell only and is not permanent) type `export PATH=/opt/idl/idl/bin:/opt/trackvis:$PATH`

* the path is searched in order from left to right when you type a program name at the prompt, so if a program exists in two directories on your path, the shell uses the first one it finds in that order.
* you can choose to run a specific program regardless of the order it appears on the path by specifying the full path (eg. `/usr/bin/ldd`).  In this case the program needn't be on the path at all.
* to change your path automatically for every shell, add the above `export PATH=...` statement to the .bashrc file in your home directory.  (just at the end is fine).  Then open a new shell, or log out and back in again, or type `source .bashrc` at your prompt to make sure your shell sees the new definitions.
* to run a program located in your current directory (if that current directory isn't on the path), type `./programname` (if the program is called 'programname').
* to see your current path type `echo $PATH` at the prompt
* to see all the currently defined environment variables for the current shell type `env`.
* to see what program the shell is running use 'which'.  For example, if you want to find the full path of the program that is running when you type `true` at the command line, type `which true`.  The program must already be found in your path directories.
* to find arbitrary files which are on the local drive, you can sometimes use `locate`.  for example,
`locate trackvis`.  The locate database is updated periodically (say, midnight every day).

Sometimes it is advantageous to define related environment variables (including the path) together in a single file.  For example, you can create a file called 'experimental-tool-suite-env.sh' which sets up your path to point to a new experimental version of your tool set installed somewhere else than the standard version and/or sets up the environment variables (data directories, etc) for a test run.

When you want to use this set of environment variables at your current shell, you can type
`source experimental-tool-suite.sh` at the prompt.  This will pull all variables defined in the file into your current shell.  A short hand for the same command is `. experimental-tool-suite.sh`.
