### ISSUE TITLE
please troubleshoot rama's external drive

### ISSUE THREAD

**Issue by stowler** [CVNRneuroimaging/infrastructure#159]
Hi Rob @rrmm,

Keith provided a drive and external SATA <-> USB adapter for rama but I can't get rama to recognize it (e.g., never appears in gparted, not seeing any obvious listing from lspci). Would you mind getting this working so that I can use rama? 

I'll keep myself isolated to pano until this is resolved, so feel free to reboot rama at will during your troubleshooting.

Thanks,
Stephen

**Comment by rrmm** [comment]
I can probably address this next week if you're around sometime.  what times are good for you?

I didn't see any plugins of a usb disk, just the dell keyboard in the logs.   What's the make and model of it?  Was the disk spinning and external power working?  Is it recognized in any other computers?

**Comment by stowler** [comment]
Hi Rob,

I unplugged and replugged it between 11:52:38 and 11:53:11 system time today.

The disk is spinning the and LED is lit. It's an Anker usb 3.0 to SATA adapter that Keith provided with a recertified 3TB Seagate drive. Haven't had time to try it on any other machines.

Times I could meet you in WMB this week (do you not have WMB keys yet?):
- after 2p today
- after 2p Thursday
- anytime Friday

**Comment by rrmm** [comment]
> Hi Rob,
> 
> I unplugged and replugged it between 11:52:38 and 11:53:11 system time
> today.
> 
> The disk is spinning the and LED is lit. It's an Anker usb 3.0 to SATA
> adapter that Keith provided with a recertified 3TB Seagate drive. Haven't
> had time to try it on any other machines.
> 
> Times I could meet you in WMB this week (do you not have WMB keys yet?):
> - after 2p today
> - after 2p Thursday
> - anytime Friday

ok i'll drop by today after 2pm.

**Comment by rrmm** [comment]
Moved USB 3 card to a different slot.
