### ISSUE TITLE
"failed to restore all the required visuals"

### ISSUE THREAD

**Issue by stowler** [CVNRneuroimaging/infrastructure#16]
Cannot reconnect to an existing session from mac client if existing session was initiated with windows 7 client. Error:  "Failed to restore all the required visuals. Can't resume the NX session on this display.

Reproducing: 

1) initiate new session (not reconnect to existing session) using initiating client: 64-bit windows 7 x2go w/ stollen fonts folder (WAN / 16m-png)

2) disconnect from session by clicking windows' close button on the client's desktop window (i.e.,  win 7 chrome, not linux chrome, and the actual remote desktop window, not the x2go session control window)

3) try to reconnect to the session using mac os x 10.8.5 
Joes-MacBook-Pro:~ stowler-local$ uname -a
Darwin Joes-MacBook-Pro.local 12.5.0 Darwin Kernel Version 12.5.0: Sun Sep 29 13:33:47 PDT 2013; root:xnu-2050.48.12~1/RELEASE_X86_64 x86_64

…here is a screenshot of the error, and  full text of the mac's x2go client details:

![failedtorestorealltherequiredvisuals](https://f.cloud.github.com/assets/436181/2223736/45791946-9a76-11e3-86d8-0c87702bd58b.png)

NXPROXY - Version 3.5.0

Copyright (C) 2001, 2010 NoMachine.
See http://www.nomachine.com/ for more information.

Info: Proxy running in client mode with pid '1158'.
Session: Starting session at 'Thu Feb 20 16:12:55 2014'.
Info: Connecting to remote host 'localhost:31001'.
Info: Connection to remote proxy 'localhost:31001' established.
Info: Connection with remote proxy completed.
Warning: Unrecognized session type 'unix-kde-depth_32'. Assuming agent session.
Warning: Failed to read data from the X auth command.
Warning: Generated a fake cookie for X authentication.
Info: Using WAN link parameters 768/24/1/0.
Info: Using cache parameters 4/4096KB/8192KB/8192KB.
Info: Using pack method '16m-rgb-9' with session 'unix-kde-depth_32'.
Info: Using ZLIB data compression 1/1/32.
Info: Using ZLIB stream compression 1/1.
Info: No suitable cache file found.
Info: Forwarding X11 connections to display '/tmp/launch-lWICEg/org.macosforge.xquartz:0'.
Session: Session started at 'Thu Feb 20 16:12:58 2014'.
Info: Established X server connection.
Info: Using shared memory parameters 1/2048K.
x2go-WARNING-1> "Can't load translator: :/x2goclient_en_us"
x2go-WARNING-2> "Can't load translator: :/qt_en_US"

**Comment by githubsucksass** [comment]
Still a problem with 4.0.4.0.  I can create a new session, but when I reconnect, I get the "Failed to restore all the required visuals" error.

**Comment by SaschaZorn** [comment]
Please fix this issue somehow! Either by adding the necessary parameters as default parameters or by fixing the root cause. Its ridiculous that I have to google for this error to resume a session on my local linux machine when I create it from a Windows client!

**Comment by kangjinsong** [comment]
(https://gist.github.com/stowler/9921780)：//gist.github.com/stowler/9921780[](https://gist.github.com/stowler/9921780)
“Launch win7 x2go client xservers in windowed mode (not full screen)”.
Can you tell me what is "windowed mode"?

**Comment by kangjinsong** [comment]
#16 (comment)    “Launch win7 x2go client xservers in windowed mode (not full screen)”.
I have encountered this problem. Can you tell me what is "windowed mode"?
