### ISSUE TITLE
Localrama1 Slow

### ISSUE THREAD

**Issue by simonero** [CVNRneuroimaging/infrastructure#161]
Processing on localrama1 is very slow.  No lag like before - but processing that takes about ~5sec locally is taking 3-5min.  To use a simple AFNI script, maxing out single core with very minimal usage of others (and minimal memory usage).  Will likely make my tractography program take days to run!  Can't work on data for Dr. Mareci until fixed.

Thank youuu!

**Comment by kmcgregor123456** [comment]
I'll look at it in a couple of minutes, it's probably permissions based.

Best,

---

Keith McGregor, PhD
Atlanta VA CVNR
Emory University
www.varrd.emory.eduhttp://ww.varrd.emory.edu

On Dec 7, 2015, at 21:44, simonero <notifications@github.com<mailto:notifications@github.com>> wrote:

Processing on localrama1 is very slow. No lag like before - but processing that takes about ~5sec locally is taking 3-5min. To use a simple AFNI script, maxing out single core with very minimal usage of others (and minimal memory usage). Will likely make my tractography program take days to run! Can't work on data for Dr. Mareci until fixed.

Thank youuu!

—
Reply to this email directly or view it on GitHubhttps://github.com/CVNRneuroimaging/infrastructure/issues/161.

---

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).
