### ISSUE TITLE
Freesurfer & IDL @rama

### ISSUE THREAD

**Issue by simonero** [CVNRneuroimaging/infrastructure#162]
I need freesurfer's license placed in the correct place on rama + I need IDL.  I put the necessary files in one of my folders, they just need to be moved:

cp /data/localdatarama1/00.Supporting_Files/freesurferFiles/license.txt /usr/local/freesurfer

mkdir /usr/local/idl
cp /data/localdatarama1/00.Supporting_Files/IDLfiles/idl.tar.bz /usr/local/idl

then that needs to be unzipped

Thank you!

**Comment by rrmm** [comment]
done
