### ISSUE TITLE
need /opt/PanTrack folder to run program

### ISSUE THREAD

**Issue by simonero** [CVNRneuroimaging/infrastructure#164]
Hey,

Can one of y'all please make a folder on pano called /opt/PanTrack that I have full access too so I can test out my program on this different machine?

Thank you!

**Comment by rrmm** [comment]
> Hey,
> 
> Can one of y'all please make a folder on pano called /opt/PanTrack that I
> have full access too so I can test out my program on this different
> machine?

I copied it over.  Check it out to make sure it stayed intact.
Do you need anything else in the /opt dir from rama?

**Comment by simonero** [comment]
> I copied it over.  Check it out to make sure it stayed intact.
> Do you need anything else in the /opt dir from rama?

Thank you so much!  I don't think so for now so I'll close this, but if I realize otherwise I'll let you know.  =)
