### ISSUE TITLE
Can't get on Pano.

### ISSUE THREAD

**Issue by simonero** [CVNRneuroimaging/infrastructure#165]
This is the error I get.  Thoughts?

<img width="511" alt="screen shot 2016-04-07 at 9 09 40 am" src="https://cloud.githubusercontent.com/assets/8782288/14352086/bb4015ba-fca0-11e5-835e-d732dd0e8d4f.png">

Also, ssh on my terminal window (ie not x2go) works.  But I got this message:

> 219 packages can be updated.
> 133 updates are security updates.

**Comment by kmcgregor123456** [comment]
The updates I will handle. Those are just simply system updates.

The x2go error appears to be a transient font error.

# 

Keith M. McGregor, PhD
VA RR&D Atlanta CVNR
Emory University, Department of Neurology
352.359.8084
http://www.varrd.emory.edu

**Comment by simonero** [comment]
Well I can get on pano now but not rama...

X2GO crashes/exits, after i put in my password and try to connect.  I haven't been able to log in all week, except through SSH which is a problem because I need to use FSL and multiple windows to troubleshoot.

**Comment by rrmm** [comment]
does the crash happen only when you restore an old session (reconnect to a
running session)?  or even when starting a new session?
