### ISSUE TITLE
Need Pano Location

### ISSUE THREAD

**Issue by simonero** [CVNRneuroimaging/infrastructure#173]
@kmcgregor123456 @rrmm 

I need a location to process on pano locally.  Don't care where just that it's local.  I will be storing/generating 34GB of space and I don't need to keep it long-term.  I need 2.5days for this to run, so I'm hoping to get it finished far enough to share diagnostics by the Thursday meeting.

Can i have a path+permissions please?

Thanks!

**Comment by kmcgregor123456** [comment]
Working on this now

**Comment by simonero** [comment]
@kmcgregor123456  Thanks for doing this.  Very helpful.

The "newer" error that is very consistent was recreated during processing on pano.  This indicates that the problem is not rama-specific.  I also received a window with a crash error, like I do variably get on rama.  The error, like usual, occurred while the c++ program track_network was sleeping.  However, looking more closely at the crash, it does appear to have occurred in relation to a file associated with the error.

Now that I can assume some consistency between rama and pano, I'm going to focus on getting my program to work so I can process data and move on.  I'm hoping this process will elucidate whether or not the problem is ROI related.  I don't need to use pano for this, but it will speed up the process if I look at ROIs and code as the source concurrently on rama and pano.  Let me know if my use of computing resources on pano is an issue and I will stop.
