### ISSUE TITLE
please configure and test DICOM receiver

### ISSUE THREAD

**Issue by stowler** [CVNRneuroimaging/infrastructure#82]
Over a few weeks I tested OsiriX as our DICOM receiver on telomere.birc.emory.edu (running Mavericks 10.9.4).

  It worked well enough until telomere powered down in the middle of one night.
  In response Keith rebuilt telomere from scratch and he is going to put it on
  backup power.

  There are a few decisions for you to make if you're going to continue running OsiriX as
  a first-stop DICOM receiver.

  1. Should you configure the OS for single-account configuration with lab-known
  password, or individual user logins with access to a shared Osirix database?  I
  can't recommend a single-account configuration, and if you are going to use a
  single-account configuration I recommend against the username "Service" Keith
  is currently using (makes parsing logs difficult).

  2. How are you going to ensure that receiver/store preferences don't get
  changed by users? At minimum I recommend that you set OsiriX to pull its
  preferences from a URL at startup (Preferences -> General -> Synchronize
  preferences at startup with url).  I uploaded my test period's OsiriX
  [preferences][] to the infrastructure repo. Feel free to diff that file against
  your configured preferences, or manually load it into OsiriX (Preferences ->
  General -> Load Preferences).

  3. How are you going to ensure security? I recommend careful firewall rules,
  and turning off all unnecessary OsiriX services (including Preferences -> Web
  Server)

  [preferences]: https://github.com/CVNRneuroimaging/infrastructure/commit/1bd16439eedfcb9d2afc79c75f5ece4e6bded351

  If it turns out that you're not happy with OsiriX, considering implementing
  something more robust like [XNAT](http://www.xnat.org/).

**Comment by kmcgregor123456** [comment]
Close. However, a note will be made to investigators reminding them of responsibility of xferring data from telomere to hippostore.
